config/routes.rb
TourneurFormation::Application.routes.draw do
  devise_for :users

  resources :contacts do
	  collection do
		  get 'search'
		end
	end

  root :to => 'Contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_presence_of :last_name
	validates_length_of :last_name, :minimum => 1
	
	has_and_belongs_to_many :users
	
	self.per_page = 3
	
	def self.search(last_name)
		Contact.find_all_by_last_name(last_name)
	end
	
	def as_json(opts={})
		{ :first_name => self.first_name, :last_name => self.last_name }
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				:token_authenticatable, :confirmable, :lockable

  before_validation :ensure_authentication_token

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :nickname, :password, :password_confirmation, :remember_me
  has_and_belongs_to_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	before_filter :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	skip_before_filter :authenticate_user!, :only => [:show, :index]
	
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate :page => params[:page]
		render(@contacts, :layout => false)  if request.xhr?
 
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
			format.xml { render xml: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :ok }
    end
  end

  def search
	  @contacts = Contact.search(params[:keyword])
    render :action => "index"
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.haml
%tr
  %td= contact.first_name
  %td= contact.last_name
  %td= link_to 'Show', contact
  - if user_signed_in?
    %td= link_to 'Edit', edit_contact_path(contact)
    %td= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete

app/views/contacts/_form.html.haml
= simple_form_for @contact do |f|
  = f.error_notification
  = f.input :first_name
  = f.input :last_name
  = f.button :submit

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

= form_tag(search_contacts_path, :method => "get") do
  = label_tag :keyword, t("search_for")
  = text_field_tag :keyword
  = submit_tag t("search_for")
  

%table#matable
  %tr
    %th First name
    %th Last name
    %th
    %th
    %th

  = render @contacts

= link_to "J'en veux plus", "javascript:", {:id => "more_contacts"}

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @contact.first_name
%p
  %b Last name:
  = @contact.last_name

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TourneurFormation
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if flash[:notice].present?
      .notice= flash[:notice]

    - if flash[:error].present?
      .notice= flash[:error]

    - if flash[:alert].present?
      .notice= flash[:alert]
    
    %ul
       
      - if user_signed_in?
        %li= "Hello #{current_user.nickname}"
      = render "devise/menu/registration_items"
      = render "devise/menu/login_items"
        
    
    = yield